apiVersion: apps/v1 
kind: Deployment
metadata:
  name: "$Username-docker-wine"
  labels:
    app: "$Username-docker-wine"
spec:
  selector:
    matchLabels:
      app: "$Username-docker-wine"
      client: $Username
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "$Username-docker-wine"
        client: $Username
    spec:
      containers:
      - image: scottyhardy/docker-wine
        name: "$Username-docker-wine"
        env:
        - name: RDP_SERVER
          value: "yes"
        - name: USER_NAME
          value: $Username
        - name: PASSWD
          value: $Password
        
---
apiVersion: v1
kind: Service
metadata:
  name: "$Username-service"
  labels:
    app: $Username
spec:
  ports:
    - port: 3389
  selector:
    app: $Username
    tier: frontend
  type: LoadBalancer
