apiVersion: v1 
kind: Deployment
metadata:
  name: mydocker-wine
  labels:
    app: docker-wine
spec:
  selector:
    matchLabels:
      app: docker-wine
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docker-wine
        tier: frontend
    spec:
      containers:
      - image: scottyhardy/docker-wine
        name: docker-wine
        env:
        - name: RDP_SERVER
          value: yes